[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/api/server.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
